// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // PwnGuideSidebar: [{type: 'autogenerated', dirName: 'pwn'}],
  // CTFSidebar: [{type: 'autogenerated', dirName: 'ctf'}],
  // But you can create a sidebar manually
  
  PwnGuideSidebar: [
    {
      type: 'doc',
      id: 'pwn',
      label: "Welcome"
    },
    
    {
      type: 'category',
      label: 'Environments',
      link: {
        type: 'generated-index',
        title: 'Environments',
        description: 'Environments to target with Enumeration and Attacking techniques',
        slug: '/env',
        keywords: ['guides'],
        image: '/img/axe-svgrepo-com.svg',
      },
      items: [
        {
          type: 'category',
          label: 'Windows',
          link: {
            type: 'generated-index',
            title: 'Windows',
            description: 'Windows Enumeration and Attacks',
            slug: '/env/windows',
            keywords: ['guides'],
            image: '/img/axe-svgrepo-com.svg',
          },
          items: [{type: 'autogenerated', dirName: 'env/windows'}],
        },
        {
          type: 'category',
          label: 'Linux',
          link: {
            type: 'generated-index',
            title: 'Linux',
            description: 'Linux Enumeration and Attacks',
            slug: '/env/linux',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [{type: 'autogenerated', dirName: 'env/linux'}]
        },
        {
          type: 'category',
          label: 'Active Directory',
          link: {
            type: 'generated-index',
            title: 'Active Directory',
            description: 'Active Directory Enumeration and Attacks',
            slug: '/env/active-directory',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [{type: 'autogenerated', dirName: 'env/active-directory'}]
        },
        {
          type: 'category',
          label: 'Web',
          link: {
            type: 'generated-index',
            title: 'Web-based Attacks',
            description: 'Website Enumeration and Attacks',
            slug: '/env/web',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [{type: 'autogenerated', dirName: 'env/web-hacking'}]
        },
        {
          type: 'category',
          label: 'Hardware',
          link: {
            type: 'generated-index',
            title: 'Hardware Attacks',
            description: 'Hardware Enumeration and Attacks',
            slug: '/env/hardware',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [{type: 'autogenerated', dirName: 'env/hardware'}]
        },
        {
          type: 'category',
          label: 'Misc',
          link: {
            type: 'generated-index',
            title: 'Miscellaneous',
            description: 'Miscellaneous Hacking techniques',
            slug: '/env/misc',
            keywords: ['guides'],
            image: '/img/docusaurus.png',
          },
          items: [{type: 'autogenerated', dirName: 'env/misc'}]
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      link: {
        type: 'generated-index',
        title: 'Hacking tools',
        description: 'Tool Guides',
        slug: '/tools',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: 'Evasion',
      link: {
        type: 'generated-index',
        title: 'Evasion',
        description: 'Evade Detection',
        slug: '/evasion',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{type: 'autogenerated', dirName: 'evasion'}],
    },
    {
      type: 'category',
      label: 'Recon',
      link: {
        type: 'generated-index',
        title: 'Reconnaisance',
        description: 'Reconnaisance Techniques for enumeration targets',
        slug: '/recon',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{type: 'autogenerated', dirName: 'recon'}],
    },
    {
      type: 'category',
      label: 'Services',
      link: {
        type: 'generated-index',
        title: 'Services',
        description: 'General information on how to identify and interact with common services',
        slug: '/services',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{type: 'autogenerated', dirName: 'services'}],
    },
    {
      type: 'category',
      label: 'Tunneling',
      link: {
        type: 'generated-index',
        title: 'Tunneling',
        description: 'General information on how to identify and interact with common services',
        slug: '/tunneling',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{type: 'autogenerated', dirName: 'tunneling'}],
    },
    {
      type: 'category',
      label: 'Lateral Movement',
      link: {
        type: 'generated-index',
        title: 'Lateral Movement',
        description: 'General information on how to identify and interact with common services',
        slug: '/lateral-movement',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{type: 'autogenerated', dirName: 'lateral-movement'}],
    },
    {
      type: 'category',
      label: 'Pivoting',
      link: {
        type: 'generated-index',
        title: 'Pivoting',
        description: 'General information on how to identify and interact with common services',
        slug: '/pivoting',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{type: 'autogenerated', dirName: 'pivoting'}],
    },
    {
      type: 'category',
      label: 'Misc',
      link: {
        type: 'generated-index',
        title: 'Miscellaneous Techniques',
        description: 'General information on how to identify and interact with common services',
        slug: '/misc',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: [{type: 'autogenerated', dirName: 'misc'}],
    },
  ],
   
};

export default sidebars;